### ISSUE TITLE
出现网络错误，怎么解决呢？

### ISSUE THREAD

**Issue by SupperSpiderMan** [BigMeat233/DZTicketClient#4]
打开http://localhost:8080/ 出现网络错误

**Comment by wujiyu115** [comment]
server端好像没开源，     https://github.com/BigMeat233/DZTicketClient/blob/4af16e83c7b99791f579f623ebb0eb3a80815630/src/utils/Network/Http.js#L7  这个地方得用开发者的服务用 http://t.og.gl

**Comment by BigMeat233** [comment]
可以取README中的release包，按照视频操作即可拉起本地service

**Comment by BigMeat233** [comment]
地址：https://github.com/BigMeat233/DZTicketClient/releases/download/v1.2.8/DZTicket.zip
或者：http://vpn.og.gl/DZTicket.zip
